### ISSUE TITLE
🛠️ beacon-tools repo setup

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/beacon-tools#1]
# Summary

Create a github repository for GA4GH Beacon related tools

# Tasks

- [x] Create a public Repo
    - MIT License
    - default README
- [x] Grant permissions to DRS devs
- [x] Protect `main`
- [x] Turn on Issues, Discussions
- [x] Commit default .editorconfig
- [x] Commit default .gitattributes

# Acceptance Criteria

- [x] `beacon-tools` repo exists
- [x] MIT License file exists
- [x] README exists
- [x] DRS devs have write permissions
- [x] `main` requires approved PRs with checks passing
- [x] Issues and Discussions are available for the repo
- [x] Repo contains default .editorconfig, .gitattributes
