### ISSUE TITLE
Results Polling for Competed tasks

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/beacon-tools#123]
## Summary
Get results after task execution is finished from the submission layer 

## Acceptance Criteria
- [x] Polls submitted tasks from SAIL submission API and checks if status is complete 
- [x] If status is complete then Downloads the results crate to the project work directory
- [x] If status not complete within 5 minutes then stop the polling and return

## Tasks
- [x] Set a timer for 5 minutes
- [x] Check if job is done by checking the task's status code 
- [x] If set to done then download using sub api endpoint `/DownloadFile/<subid+1>`
- [x] If not done under 5 minutes stop polling and return
