### ISSUE TITLE
Refactor CrateSubmission to write files in memory

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/beacon-tools#124]
## Acceptance Criteria

- [ ] No saving to file storage
- [ ] ROCrate files are written in memory only
- [ ] Zip file is created in memory and uploaded to MinIO storage (using ZipBuilder library)

## Tasks

- [x] Remove bridge-workdir
- [x] Modify/Remove any methods from the ROCrate library that save to file storage. ( in RoCratesBuilder)
- [x] Parse jsonObjects for ROCrate to be serializable for ro-crate-metadata.json and write to zipBuilder
- [x] Write the html preview and add to zipBuilder
- [ ] Modify the bagit and manifest files to not use file storage
- [ ] Modify AssessBagit method 
- [ ] Add bagit files to zipBuilder
- [ ] Upload zip file to minio storage
