### ISSUE TITLE
Automated Egress Approval

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/beacon-tools#135]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Allow automated egress approval for the beacon submissions

### Acceptance Criteria

- [x] ApproveEgress as FeatureFlag
- [x] Approves Egress for a submitted task once it finishes execution

### Tasks

- [x] Add ApproveEgress FeatureFlag
- [x] Add egress config to OpenIdOptions for access token to the Egress API
- [x] Approve Egress
   - [x] get all unprocessed egress requests
   - [x] match to the submission ID
   - [x] approve individual files, and then entire request

### Confirm creation

- [x] This issue is ready
