### ISSUE TITLE
🛠️ Create Beacon Bridge Project

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/beacon-tools#2]
# Summary

Create a new ASP.NET Core Web API Project, targeting .NET8 for the BeaconBridge application

# Tasks

- [x] Create an ASP.NET Core Web API Project targeting .NET 8
    - .sln file in repo root
    - project in `app/BeaconBridge`
    - [x] Remove any unneeded template files before committing
        - [x] e.g. WeatherApiController.cs, dummy data
- [x] Create an xUnit Test project targeting .NET8
    - project in `tests/BeaconBridge.Tests`
    - in the same solution
    - [x] Remove any unneeded Template files before committing
        - [x] e.g. Initial test class Test1.cs

# Acceptance Criteria

- [x] Repo contains `BeaconBridge.sln` at the root
- [x] Repo contains a .NET8 ASP.NET Core Web API app at `app/BeaconBridge`
- [x] Repo contains a .NET8 xUnit Test project at `tests/BeaconBridge.Tests`
- [x] New apps don't contain unneeded template files
