### ISSUE TITLE
🛠️ Use standard Startup pattern for Beacon Bridge

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/beacon-tools#3]
# Summary

For consistency with other DRS (web) apps, apply the Startup pattern to the Beacon Bridge web app.

Should be able to copy from RQuestBridge or HutchAgent.

# Tasks

- [x] Copy over default Program.cs
- [x] Copy over dependent Startup bits
    - [x] CLI entrypoint
    - [x] CLI commands and helpers
    - [x] CLI Service Configuration etc
    - [x] Web entrypoint
    - [x] Web Service Configuration
    - [x] Web Pipeline Configuration
    - [x] Probably disable EF Entrypoint? (Comment out?)

# Acceptance Criteria

- [x] Program.cs is as expected
- [x] Startup folder is as expected, and all dependencies are present
- [x] EF Entrypoint is in some way disabled while EF is not used by the app
