### ISSUE TITLE
💡 Filtering Terms Beacon Endpoint

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/beacon-tools#31]
# Summary
The `/filtering_terms` endpoint returns a list of all data fields whose values may be subjected to filtering, plus the data type(s) for those fields, and/or the list of extant values for each of those data fields in the current dataset.

# Tasks
- [x] Create models for the response structure
- [x] Create endpoint 

# Acceptance Criteria
- [x] matches the beacon schema
- [x] displays the correct response structure
# Example response
```
{
    "meta": {
        "beaconId": "org.ega-archive.ga4gh-approval-beacon-test",
        "apiVersion": "v2.0.0",
        "returnedGranularity": "record",
        "receivedRequestSummary": {
            "apiVersion": "v2.0.0",
            "requestedSchemas": [],
            "filters": [],
            "requestParameters": {},
            "includeResultsetResponses": "HIT",
            "pagination": {
                "skip": 0,
                "limit": 10
            },
            "requestedGranularity": "record",
            "testMode": false
        },
        "returnedSchemas": [
            {
                "entityType": "filteringterms",
                "schema": "beacon-dataset-v2.0.0"
            }
        ]
    },
    "responseSummary": {
        "exists": false,
        "numTotalResults": 0
    },
    "response": {
        "filteringTerms": []
    },
    "beaconHandovers": [
        {
            "handoverType": {
                "id": "CUSTOM:000001",
                "label": "Project description"
            },
            "note": "Project description",
            "url": "https://www.nist.gov/programs-projects/genome-bottle"
        }
    ]
}
```
