### ISSUE TITLE
💡 Extract Filtering Terms from omop data

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/beacon-tools#34]
# Summary 
- Take rquest-omop-worker and rework to extract filters from the omop data.
 - old task: Take the script from B2RI project and turn into a small python app for extracting the filtering_terms from the data. Then write a workflow to execute it.
# Tasks
- [x] set up beacon-omop-worker from rquest version
- [x] remove code relating to rquest
- [x] write models corresponding to the omop db & beacon
- [x] write sql query for extracting the filtering_terms from the data
- [x] write the list of filtering terms to output.json
- [x] run against omop data
# Acceptance Criteria
- [x] script should be extracting the relevant filtering terms from the omop db tables
