### ISSUE TITLE
CI workflows for Beacon Bridge

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/beacon-tools#4]
# Summary

Add automated builds and tests for BeaconBridge to increase confidence in PR quality.

# Tasks

- [ ] Add labeler workflow
    - [ ] Configured to include appropriate area label(s) for BeaconBridge/Tests
- [ ] Add build workflow for BeaconBridge
    - [ ] Triggers for PRs targeting main
    - [ ] Restore dependencies
    - [ ] Ensure app builds
    - [ ] Ensure app tests pass
    - [ ] No need to publish artifacts or deploy releases (this is just for PR checking)
- [ ] Add publish workflow for BeaconBridge
    - [ ] Does everything build does
    - [ ] Triggers on push to main
    - [ ] Publishes a named and versioned artifact that could be used for release or deployment.
    - [ ] Don't actually do release or deployment
- [ ] Add release workflow for BeaconBridge
    - [ ] Refers to a publish workflow run by id
    - [ ] Manually triggered
    - [ ] Fetch the published artifacts
    - [ ] Create a versioned github release with artifacts attached

These workflows should be able to be taken and modified from HutchAgent

# Acceptance Criteria

- [ ] Build workflow runs successfully on PRs and success is required for merging
- [ ] Publish workflow works (test via temporary PR trigger)
- [ ] Publish workflow runs when pr's are merged to main
- [ ] Release workflow works (test via temporary hardcoded run id and PR trigger)
