### ISSUE TITLE
`filtering_terms` endpoint retrieves cached terms

### ISSUE THREAD

**Issue by dcl10** [Health-Informatics-UoN/beacon-tools#43]
## Description
Create a DB cache for the filtering terms. Then return the cached terms to the user.

## Tasks
- [x] DB cache for filtering terms.
- [x] get filtering_terms requests from the cache.
- [x] return them to the user.
