### ISSUE TITLE
Data seeding of filtering terms

### ISSUE THREAD

**Issue by dcl10** [Health-Informatics-UoN/beacon-tools#55]
## Description
Currently we have some hard coded filtering terms. These were removed to make room for the real ones. We need to seed some data to show off.

## Tasks
- [ ] create a data seeder in BeaconBridge
- [ ] make the seeding occur on start-up. Look at TRIPOD for an example
- [ ] Add the seed data
