### ISSUE TITLE
Deployment pipeline for BeaconBridge

### ISSUE THREAD

**Issue by dcl10** [Health-Informatics-UoN/beacon-tools#61]
## Description
Create a github workflow to deploy BeaconBridge to Azure App Service.

## Tasks
- [x] remove automatic migrations
- [x] borrow build and deployment pipelines from rcc-monitor
- [x] adapt the workflows for BeaconBridge
