### ISSUE TITLE
Create 'individuals' endpoint

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/beacon-tools#74]
## Tasks
- [x] Tim to determine query
 - [x] Beacon over OMOP static query output
    - [x] Run Tim's query locally
     - [x] GET endpoint randomly return true or false for any query other than Tim's
     - [x] GET cache queries and the random true/false value so they appear consistent
        - [x] Do an in-memory cache (ask Jon) not DB
     - [x] GET endpoint returns true for Tim's query output
