### ISSUE TITLE
💡 beacon-omop-worker individual queries

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/beacon-tools#80]
## Tasks
- [x] Change filtering terms to only include Person and Condition Occurence
- [x] Only allow filters from SNOMED code
- [x] set up subcommand for individuals: `beacon-omop-worker individuals --filters "Gender:F,SNOMED:386661006,SNOMED:271825005"
- [x] write code to execute queries on Person and Condition Occurence tables
- [x] return true or false `exists` boolean in Response Summmary 
- [x] write ResponseSummary to `output.json`
