### ISSUE TITLE
Write CrateGenerationService for beacon-omop-worker

### ISSUE THREAD

**Issue by vpnu** [Health-Informatics-UoN/beacon-tools#84]
## Tasks 
- [x] Write CrateGenerationService for beacon-omop-worker individuals workflow
- [x] Upload to minio bucket
- [x] submit to submission layer
