### ISSUE TITLE
BeaconBridge UI

### ISSUE THREAD

**Issue by dcl10** [Health-Informatics-UoN/beacon-tools#93]
## Description
BeaconBridge needs a UI for users to interact with graphically over the web.

Note: Due to some discoveries exploratory work and the short deadline, the app UI will be a separate JS app from the backend and deployed separately.

## Tasks
- [x] Create a Next.JS app to serve as the UI
- [x] Create a basic About page with some copy and form/widget for running filtering terms queries
- [x] Deploy to app service
